# Generated by Django 3.2.5 on 2021-07-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dailt_rate',
            new_name='daily_rate',
        ),
    ]
